#!/usr/bin/env bash
# 404
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed  '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=fWuieH6CPhA permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed  '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default
service nginx start
