#!/usr/bin/env bash
# comment

source_file="$1"
dest_user="$3"
dest_ip="$2"
pub_key="$4"

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$pub_key" -o StrictHostKeyChecking=no "$source_file" "$dest_user"@"$dest_ip":~/
fi
