#!/usr/bin/env bash
# Installs nginx and redirects

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sudo sed -i '/^\tserver_name.*/a \\trewrite ^\/redirect_me https:\/\/twitter.com permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
