#!/usr/bin/env bash
# qwerty
sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html 
sed -i '/^\tserver_name.*/a \\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=tRzM19XPYzI permanent;' /etc/nginx/sites-available/default
sed -i "36a \\\tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default
sudo service nginx restart
