#!/usr/bin/env bash
# password, suprisingly easy
while IFS=: read -r USERNAME PASSWORD USERID GROUPID USERIDINFO HOME_DIRECTORY COMMANDSHELL
do
	echo "The user $USERNAME is part of the $GROUPID gang, lives in $HOME_DIRECTORY and rides $COMMANDSHELL. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USERIDINFO"
done < /etc/passwd